// Code generated by go-vk from vk.xml at 2026-09-28 14:34:46.677154169 +0100 BST m=+2.168688190. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
