//go:build darwin

// Code generated by go-vk from vk.xml at 2026-09-28 14:34:46.720455999 +0100 BST m=+2.211990094. DO NOT EDIT.

package vk

import (
	"runtime"
	"unsafe"
)

// CreateMacOSSurfaceMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateMacOSSurfaceMVK.html
func CreateMacOSSurfaceMVK(instance Instance, createInfo *MacOSSurfaceCreateInfoMVK, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkMacOSSurfaceCreateInfoMVK
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateMacOSSurfaceMVK, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	runtime.KeepAlive(instance)
	runtime.KeepAlive(pCreateInfo)
	runtime.KeepAlive(pAllocator)
	runtime.KeepAlive(ptr_pSurface)

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateMacOSSurfaceMVK = &vkCommand{"vkCreateMacOSSurfaceMVK", 4, true, nil}
