// Code generated by go-vk from vk.xml at 2026-09-28 14:34:46.858663032 +0100 BST m=+2.350197053. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
