//go:build darwin

// Code generated by go-vk from vk.xml at 2026-09-28 14:34:46.968008485 +0100 BST m=+2.459542505. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_OBJECTS_EXTENSION_NAME = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION   = 2
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
