//go:build darwin

// Code generated by go-vk from vk.xml at 2026-09-28 14:34:46.864112391 +0100 BST m=+2.355646415. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
